export const data = [
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
  {
    crawl_timestamp: "2015-12-13 00:29:55 +0000",
    product_url:
      "https://www.flipkart.com/okane-printed-men-s-round-neck-t-shirt/p/itme5yq4dfzj9zzg?pid=TSHE5YQ4CDHJX4ZA",
    product_name: "Okane Printed Men's Round Neck T-Shirt",
    product_category_tree: [
      "Clothing",
      "Men's Clothing",
      "T-Shirts",
      "Okane T-Shirts",
    ],
    pid: "TSHE5YQ4CDHJX4ZA",
    retail_price: 299,
    discounted_price: 299,
    image: [
      "http://img5a.flixcart.com/image/t-shirt/4/z/at5-90099-b-green-okane-xxl-original-imae4pxjuhdbzhne.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-s-original-imae5yq5hskvjmzb.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjkhxecgwm.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xl-original-imae5yq5h23zjxad.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xqtkkpz.jpeg",
      "http://img5a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxj9xwjjszg.jpeg",
      "http://img6a.flixcart.com/image/t-shirt/4/z/a/t5-90099-b-green-okane-xxl-original-imae4pxjw3gvg2za.jpeg",
    ],
    is_FK_Advantage_product: "FALSE",
    description:
      "Open your door to the world of grilling with the sleek Spirit II E-210 gas grill. This two burner grill is built to fit small spaces, and packed with features such as the powerful GS4 grilling system, iGrill capability, and convenient side tables for placing serving trays. Welcome to the Weber family",
    product_rating: "No rating available",
    overall_rating: "No rating available",
    brand: "Okane",
    product_specifications: {
      product_specification: [
        { key: "Sleeve", value: "Half Sleeve" },
        { key: "Number of Contents in Sales Package", value: "Pack of 1" },
        { key: "Fabric", value: "Cotton" },
        { key: "Type", value: "Round Neck" },
        { key: "Pattern", value: "Printed" },
        { key: "Occasion", value: "Casual" },
        { key: "Ideal For", value: "Men's" },
        { value: "1 T Shirt" },
        { key: "Style Code", value: "T5-90099 B.GREEN" },
      ],
    },
    id: "3861dc97213e45076531ee43ee1e121c",
    rating: 1.5,
    stock: 762,
    discount: 0,
  },
];
